### ISSUE TITLE
ENH: filter with slicing

### ISSUE THREAD

**Issue by CJ-Wright** [NSLS-II/databroker#92]
Would it be possible to slice the databroker with filters on?
eg
```python
db.add_filter(bt_piLast='Billinge')
a = db[-1]
# a is the latest header from the Billinge beamtime
```

**Comment by sbillinge** [comment]
I also want this behavior, but I also want `db[-1]` to return the latest dataset regardless of filter settings.  In other words, I would like the fact that the slicing is being done on filtered data to be explicit to the user.  I

I see big problems otherwise, where some filter is set and users are not getting data that they are expecting and going nutso.

**Comment by danielballan** [comment]
> I see big problems otherwise, where some filter is set and users are not getting data that they are expecting and going nutso.

We saw the same problem. Filters do not affect slicing, and in order to avoid said "nutso" feeling, it is impossible to make them. Can't have cake and eat it too in this case.

**Comment by danielballan** [comment]
P.S. Of course, can always do:

```python
db.add_filter(bt_piLast='Billinge')
db()[-1]
```

**Comment by CJ-Wright** [comment]
Is it possible to get back all the records as a generator? That way we don't look at everything at once?

**Comment by danielballan** [comment]
I realized no one answer your last question here. It is not currently possible using the public API, but a separate query method could be added. We chose to be non-lazy here to make the common case (fetching a normal number of headers) more accessible. A compromise that shows the difficulty of building a library and a "user friendly" CLI into the same package.
